source 'http://rubygems.org'

gem 'rake'
gem 'rack'
gem 'json'
gem 'sinatra'
gem 'sqlite3'
gem 'activerecord'
gem 'sinatra-activerecord'

group :development do
  gem 'rerun', '0.9.0'
  gem 'thin', '1.6.2'
end
