#encoding: utf-8 

Category.create(title: "Спорт" ,category_id: 0)
Category.create(category_id: 1, title: "Футбол")
Category.create(category_id: 1, title: "Хокей")
Category.create(category_id: 0, title: "Історія")
Category.create(category_id: 4, title: "Історія України")
Category.create(category_id: 4, title: "Історія світу")
Quiz.create(category_id: 2, title: "Тест на знання правил футболу", description: "Детальний опис тесту")
Question.create(quiz_id: 1, title: "Скільки гравців в команді?", description: "Згідно правил на полі знаходиться 11 гравців однієї команди")
Answer.create(question_id: 1, title: "11", correct: true)
Answer.create(question_id: 1, title: "12", correct: false)
Answer.create(question_id: 1, title: "5", correct: false)
Question.create(quiz_id: 1, title: "Скільки триває один тайм?", description: "Один тайм матчу триває 45 хв. не враховуючи додаткового часу")
Answer.create(question_id: 2, title: "20хв", correct: false)
Answer.create(question_id: 2, title: "45хв", correct: true)
Answer.create(question_id: 2, title: "до останнього гравця", correct: false)
Question.create(quiz_id: 1, title: "Що відбудеться, коли гравець торкнеться м’яча рукою?", description: "Це є порушенням правил, після того як гравець торкнувся мяча рукою гра зупиняється, та назначається штрафний")
Answer.create(question_id: 3, title: "Порушенння правил", correct: true)
Answer.create(question_id: 3, title: "Штрафний удар", correct: true)
Answer.create(question_id: 3, title: "Дадуть пиріжок", correct: false)
Answer.create(question_id: 3, title: "Дадуть в голову", correct: false)
Comment.create(quiz_id: 1, text: "Гарний тест")
Comment.create(quiz_id: 1, text: "Потрібно додати питання з двома правильними відповідями")

adminRole = Role.create(name: 'admin')
moderRole = Role.create(name: 'moder')
userRole =  Role.create(name: 'user')
superadminRole = Role.create(name: 'superadmin')

user1 = userRole.users.create(username: "user123", password: "12345678", password_confirmation: "12345678", email: "user@mail.com", birthday: "2000-12-31T22:00:00.000Z")
admin1 = adminRole.users.create(username: "admin123", password: "12345678", password_confirmation: "12345678", email: "admin@mail.com", birthday: "2000-12-31T22:00:00.000Z")
moder1 = moderRole.users.create(username: "moder123", password: "12345678", password_confirmation: "12345678", email: "moder@mail.com", birthday: "2000-12-31T22:00:00.000Z")
superadmin1 = superadminRole.users.create(username: "super123", password: "12345678", password_confirmation: "12345678", email: "super@mail.com", birthday: "2000-12-31T22:00:00.000Z")

valera = userRole.users.create(username: "Valera", password: "12345678", password_confirmation: "12345678", email: "valera@mail.com", birthday: "2000-12-31T22:00:00.000Z")
ivan = userRole.users.create(username: "Ivan", password: "12345678", password_confirmation: "12345678", email: "ivan@mail.com", birthday: "2000-12-31T22:00:00.000Z")
vasyl = userRole.users.create(username: "Vasyl", password: "12345678", password_confirmation: "12345678", email: "vasyl@mail.com", birthday: "2000-12-31T22:00:00.000Z")

Permission.create(tabs: 'admin1', admin: '1', superadmin: '4')
Permission.create(tabs: 'admin2', admin: '1', superadmin: '4')
Permission.create(tabs: 'admin3', admin: '1', superadmin: '4')
Permission.create(tabs: 'admin4', admin: '1', superadmin: '4')
Permission.create(tabs: 'admin5', admin: '1', superadmin: '4')
Permission.create(tabs: 'admin6', admin: '1', superadmin: '4')
Permission.create(tabs: 'admin7', admin: '1', superadmin: '4')

Permission.create(tabs: 'moder1', moder: '2', superadmin: '4')
Permission.create(tabs: 'moder2', moder: '2', superadmin: '4')
Permission.create(tabs: 'moder3', moder: '2', superadmin: '4')

Permission.create(tabs: 'menu1', admin: '1', moder: '2', user: '3', superadmin: '4')
Permission.create(tabs: 'menu2', admin: '1', superadmin: '4')
Permission.create(tabs: 'menu3', moder: '2', superadmin: '4')
