#encoding: utf-8 

Category.create(title: "Спорт" ,category_id: 0)
Category.create(category_id: 1, title: "Футбол")
Quiz.create(category_id: 2, title: "Тест на знання правил футболу", description: "Детальний опис тесту")
Question.create(quiz_id: 1, title: "Скільки гравців в команді?", description: "")
Answer.create(question_id: 1, title: "11", correct: true)
Answer.create(question_id: 1, title: "12", correct: false)
Answer.create(question_id: 1, title: "5", correct: false)
Question.create(quiz_id: 1, title: "Скільки триває один тайм?", description: "")
Answer.create(question_id: 2, title: "20хв", correct: false)
Answer.create(question_id: 2, title: "45хв", correct: true)
Answer.create(question_id: 2, title: "до останнього гравця", correct: false)
Question.create(quiz_id: 1, title: "Що відбудеться, коли гравець торкнеться м’яча рукою?", description: "")
Answer.create(question_id: 3, title: "Порушенння правил", correct: true)
Answer.create(question_id: 3, title: "Штрафний удар", correct: true)
Answer.create(question_id: 3, title: "Дадуть пиріжок", correct: false)
Answer.create(question_id: 3, title: "Дадуть в голову", correct: false)
Category.create(title: "Комп'ютери" ,category_id: 0)
Category.create(title: "Туризм" ,category_id: 0)
Category.create(title: "Країни" ,category_id: 4)
Category.create(title: "Хокей" ,category_id: 1)
Category.create(title: "Баскетбол" ,category_id: 1)
Category.create(title: "Комплектуючі" ,category_id: 3)
Category.create(title: "Програмування" ,category_id: 3)
Category.create(title: "Мережі" ,category_id: 3)
Category.create(title: "Столиці" ,category_id: 4)
Category.create(title: "Гори" ,category_id: 4)
Quiz.create(category_id: 6, title: "Тест на знання правил хокею", description: "Опис")
Quiz.create(category_id: 8, title: "Тест на знання комплектуючих", description: "Опис")
Quiz.create(category_id: 9, title: "Тест на знання програмування", description: "Опис")
Quiz.create(category_id: 10, title: "Тест на знання мереж", description: "Опис")
Quiz.create(category_id: 10, title: "Тест на знання мережевих протоколів", description: "Опис")
Quiz.create(category_id: 5, title: "Тест на знання географії", description: "Опис")
Tag.create(quiz_id: 1, tag: "teg1")
Tag.create(quiz_id: 1, tag: "teg2")
Tag.create(quiz_id: 2, tag: "teg3")
Tag.create(quiz_id: 3, tag: "teg5")
Tag.create(quiz_id: 4, tag: "teg6")
Tag.create(quiz_id: 4, tag: "teg1")
Tag.create(quiz_id: 5, tag: "teg2")
Tag.create(quiz_id: 5, tag: "teg7")
Tag.create(quiz_id: 6, tag: "teg8")
